/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_gui;

import java.awt.*;

/**
 *
 * @author Huy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        initComponents();
        setLocationRelativeTo(null);
        Phong_Table.getTableHeader().setFont(new Font("UTM Avo", Font.BOLD, 12));
        Phong_Table.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        btnINFO = new javax.swing.JLabel();
        btnLSDP = new javax.swing.JLabel();
        btnQLP = new javax.swing.JLabel();
        btnQLKH = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        LogoLable = new javax.swing.JLabel();
        btnDX = new javax.swing.JLabel();
        BackGr = new javax.swing.JLabel();
        TabPanel = new javax.swing.JTabbedPane();
        Main_Panel = new javax.swing.JPanel();
        Info_Panel = new javax.swing.JPanel();
        SDT_Text = new javax.swing.JLabel();
        SDT_Backgr = new javax.swing.JLabel();
        ID_Text = new javax.swing.JLabel();
        ID_Backgr = new javax.swing.JLabel();
        Name_Text = new javax.swing.JLabel();
        Name_Backgr = new javax.swing.JLabel();
        btnDMK = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        QLP_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        TypeRoomComboBox = new javax.swing.JComboBox<>();
        ID_TextField = new javax.swing.JTextField();
        BookID_TextField = new javax.swing.JTextField();
        CustomerID_TextField = new javax.swing.JTextField();
        btnFind = new javax.swing.JLabel();
        btnBook = new javax.swing.JLabel();
        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnCheckIn = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Phong_Table = new javax.swing.JTable();
        KH_Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        NV_Panel = new javax.swing.JPanel();
        LSDP_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Manager");
        setBackground(new java.awt.Color(250, 249, 248));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnExit.png"))); // NOI18N
        btnExit.setText("jLabel2");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        mainPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        btnINFO.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnINFO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnINFO1.png"))); // NOI18N
        btnINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnINFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnINFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnINFOMouseExited(evt);
            }
        });
        mainPanel.add(btnINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 70));

        btnLSDP.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnLSDP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLSDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnLSP1.png"))); // NOI18N
        btnLSDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLSDPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLSDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLSDPMouseExited(evt);
            }
        });
        mainPanel.add(btnLSDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 260, 70));

        btnQLP.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnQLP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQLP1.png"))); // NOI18N
        btnQLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLPMouseExited(evt);
            }
        });
        mainPanel.add(btnQLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 70));

        btnQLKH.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnQLKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQKH1.png"))); // NOI18N
        btnQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLKHMouseExited(evt);
            }
        });
        mainPanel.add(btnQLKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 70));

        btnQLNV.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnQLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQNV1.png"))); // NOI18N
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLNVMouseExited(evt);
            }
        });
        mainPanel.add(btnQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 70));

        header.setBackground(new java.awt.Color(250, 249, 248));
        header.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        header.setText("    Màn hình chính");
        header.setOpaque(true);
        mainPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        LogoLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/logoMainForm.png"))); // NOI18N
        LogoLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLableMouseClicked(evt);
            }
        });
        mainPanel.add(LogoLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 190));

        btnDX.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        btnDX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnDX1.png"))); // NOI18N
        btnDX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDXMouseExited(evt);
            }
        });
        mainPanel.add(btnDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 840, -1, -1));

        BackGr.setBackground(new java.awt.Color(250, 249, 248));
        BackGr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/Background1.png"))); // NOI18N
        mainPanel.add(BackGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 900));

        Main_Panel.setBackground(new java.awt.Color(250, 249, 248));
        Main_Panel.setMinimumSize(new java.awt.Dimension(935, 872));
        Main_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabPanel.addTab("tab7", Main_Panel);

        Info_Panel.setBackground(new java.awt.Color(250, 249, 248));
        Info_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        Info_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SDT_Text.setBackground(new java.awt.Color(250, 249, 248));
        SDT_Text.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        SDT_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SDT_Text.setText("Your Phone Number");
        SDT_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SDT_Text.setOpaque(true);
        Info_Panel.add(SDT_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 610, 50));

        SDT_Backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/SDT_Backgr.png"))); // NOI18N
        Info_Panel.add(SDT_Backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 800, 60));

        ID_Text.setBackground(new java.awt.Color(250, 249, 248));
        ID_Text.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        ID_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID_Text.setText("Your ID");
        ID_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ID_Text.setOpaque(true);
        Info_Panel.add(ID_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 610, 50));

        ID_Backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/ID_Backgr.png"))); // NOI18N
        Info_Panel.add(ID_Backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 800, 60));

        Name_Text.setBackground(new java.awt.Color(250, 249, 248));
        Name_Text.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        Name_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_Text.setText("Your Full Name");
        Name_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Name_Text.setOpaque(true);
        Info_Panel.add(Name_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 610, 50));

        Name_Backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/Name_Backgr.png"))); // NOI18N
        Info_Panel.add(Name_Backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 800, 60));

        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnDMK1.png"))); // NOI18N
        btnDMK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnDMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDMKMouseExited(evt);
            }
        });
        Info_Panel.add(btnDMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 260, 70));

        jLabel2.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFO");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        Info_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 60));

        TabPanel.addTab("tab1", Info_Panel);

        QLP_Panel.setBackground(new java.awt.Color(250, 249, 248));
        QLP_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        QLP_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHÒNG");
        QLP_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 40));

        StatusComboBox.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang trống", "Đang ở", "Đã đặt", "Đang sửa" }));
        StatusComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(StatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 390, 40));

        TypeRoomComboBox.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        TypeRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Deluxe", "Royal", "President" }));
        TypeRoomComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(TypeRoomComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 390, 40));

        ID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        ID_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ID_TextField.setText("Room ID");
        ID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 390, 40));

        BookID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        BookID_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BookID_TextField.setText("Booking ID");
        BookID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(BookID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 390, 40));

        CustomerID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        CustomerID_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CustomerID_TextField.setText("Customer ID");
        CustomerID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(CustomerID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 390, 40));

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnFind1.png"))); // NOI18N
        btnFind.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindMouseExited(evt);
            }
        });
        QLP_Panel.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 260, 50));

        btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnBook1.png"))); // NOI18N
        btnBook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookMouseExited(evt);
            }
        });
        QLP_Panel.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 120, 50));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnAdd1.png"))); // NOI18N
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        QLP_Panel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 120, 50));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnUpd1.png"))); // NOI18N
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        QLP_Panel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 120, 50));

        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnCkIN1.png"))); // NOI18N
        btnCheckIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckInMouseExited(evt);
            }
        });
        QLP_Panel.add(btnCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 120, 50));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnDel1.png"))); // NOI18N
        btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        QLP_Panel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 120, 50));

        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnCkO1.png"))); // NOI18N
        btnCheckOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckOutMouseExited(evt);
            }
        });
        QLP_Panel.add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 120, 50));

        btnClear.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        QLP_Panel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 260, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/CusID_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 540, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/BookID_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 540, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/Status_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 540, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/TypeRoom_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 540, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/ID_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 540, 50));

        Phong_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Type Of Room", "Status", "Booking ID", "Customer ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Phong_Table.setFocusable(false);
        Phong_Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Phong_Table.setOpaque(false);
        Phong_Table.setRowHeight(25);
        Phong_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Phong_Table.setShowVerticalLines(false);
        Phong_Table.getTableHeader().setResizingAllowed(false);
        Phong_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Phong_Table);

        QLP_Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 860, 490));

        TabPanel.addTab("tab2", QLP_Panel);

        KH_Panel.setBackground(new java.awt.Color(250, 249, 248));
        KH_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        KH_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel8.setText("QUẢN LÝ KHÁCH HÀNG");
        KH_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 70));

        TabPanel.addTab("tab4", KH_Panel);

        NV_Panel.setBackground(new java.awt.Color(250, 249, 248));
        NV_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        NV_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabPanel.addTab("tab5", NV_Panel);

        LSDP_Panel.setBackground(new java.awt.Color(250, 249, 248));
        LSDP_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        LSDP_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabPanel.addTab("tab6", LSDP_Panel);

        mainPanel.add(TabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 910));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseEntered
        btnQLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQLP2.png")));
    }//GEN-LAST:event_btnQLPMouseEntered

    private void btnQLPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseExited
        btnQLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQLP1.png")));
    }//GEN-LAST:event_btnQLPMouseExited

    private void btnQLKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseEntered
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQKH2.png")));
    }//GEN-LAST:event_btnQLKHMouseEntered

    private void btnQLKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseExited
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQKH1.png")));
    }//GEN-LAST:event_btnQLKHMouseExited

    private void btnQLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseEntered
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQNV2.png")));
    }//GEN-LAST:event_btnQLNVMouseEntered

    private void btnQLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseExited
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQNV1.png")));
    }//GEN-LAST:event_btnQLNVMouseExited

    private void btnDXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDXMouseEntered
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnDX2.png")));
    }//GEN-LAST:event_btnDXMouseEntered

    private void btnDXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDXMouseExited
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnDX1.png")));
    }//GEN-LAST:event_btnDXMouseExited

    private void btnDXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDXMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_btnDXMouseClicked

    private void btnQLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseClicked
        TabPanel.setSelectedComponent(QLP_Panel);
    }//GEN-LAST:event_btnQLPMouseClicked

    private void btnQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseClicked
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQKH2.png")));
    }//GEN-LAST:event_btnQLKHMouseClicked

    private void btnQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseClicked
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnQNV2.png")));
    }//GEN-LAST:event_btnQLNVMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnExit2.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnExit.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnLSDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLSDPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLSDPMouseClicked

    private void btnLSDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLSDPMouseEntered
        btnLSDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnLSP2.png")));
    }//GEN-LAST:event_btnLSDPMouseEntered

    private void btnLSDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLSDPMouseExited
        btnLSDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnLSP1.png")));
    }//GEN-LAST:event_btnLSDPMouseExited

    private void btnINFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINFOMouseClicked
        TabPanel.setSelectedComponent(Info_Panel);
    }//GEN-LAST:event_btnINFOMouseClicked

    private void btnINFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINFOMouseEntered
        btnINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnINFO2.png")));
    }//GEN-LAST:event_btnINFOMouseEntered

    private void btnINFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINFOMouseExited
        btnINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnINFO1.png")));
    }//GEN-LAST:event_btnINFOMouseExited

    private void btnDMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseEntered
        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnDMK2.png")));
    }//GEN-LAST:event_btnDMKMouseEntered

    private void btnDMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseExited
        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/btnDMK1.png")));
    }//GEN-LAST:event_btnDMKMouseExited

    private void btnDMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DMK_Panel().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnDMKMouseClicked

    private void btnFindMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseEntered
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnFind2.png")));
    }//GEN-LAST:event_btnFindMouseEntered

    private void btnFindMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseExited
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnFind1.png")));
    }//GEN-LAST:event_btnFindMouseExited

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindMouseClicked

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
       btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnAdd2.png")));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
       btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnAdd1.png")));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnUpd2.png")));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnUpd1.png")));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnCheckInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckInMouseEntered
        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnCkIN2.png")));
    }//GEN-LAST:event_btnCheckInMouseEntered

    private void btnCheckInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckInMouseExited
        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnCkIN1.png")));
    }//GEN-LAST:event_btnCheckInMouseExited

    private void btnCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckInMouseClicked

    private void btnCheckOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckOutMouseEntered
        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnCkO2.png")));
    }//GEN-LAST:event_btnCheckOutMouseEntered

    private void btnCheckOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckOutMouseExited
       btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnCkO1.png")));
    }//GEN-LAST:event_btnCheckOutMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
       btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnDel2.png")));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnDel1.png")));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseEntered
       btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnBook2.png")));
    }//GEN-LAST:event_btnBookMouseEntered

    private void btnBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseExited
        btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_gui/pic/QLP_pic/btnBook1.png")));
    }//GEN-LAST:event_btnBookMouseExited

    private void btnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookMouseClicked

    private void btnCheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckOutMouseClicked

    private void LogoLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLableMouseClicked
        TabPanel.setSelectedComponent(Main_Panel);
    }//GEN-LAST:event_LogoLableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGr;
    private javax.swing.JTextField BookID_TextField;
    private javax.swing.JTextField CustomerID_TextField;
    private javax.swing.JLabel ID_Backgr;
    private javax.swing.JLabel ID_Text;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JPanel Info_Panel;
    private javax.swing.JPanel KH_Panel;
    private javax.swing.JPanel LSDP_Panel;
    private javax.swing.JLabel LogoLable;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel NV_Panel;
    private javax.swing.JLabel Name_Backgr;
    private javax.swing.JLabel Name_Text;
    private javax.swing.JTable Phong_Table;
    private javax.swing.JPanel QLP_Panel;
    private javax.swing.JLabel SDT_Backgr;
    private javax.swing.JLabel SDT_Text;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JComboBox<String> TypeRoomComboBox;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnBook;
    private javax.swing.JLabel btnCheckIn;
    private javax.swing.JLabel btnCheckOut;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDMK;
    private javax.swing.JLabel btnDX;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnFind;
    private javax.swing.JLabel btnINFO;
    private javax.swing.JLabel btnLSDP;
    private javax.swing.JLabel btnQLKH;
    private javax.swing.JLabel btnQLNV;
    private javax.swing.JLabel btnQLP;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
